import LogoSVG from "@/components/Logo";
import Menu from "@/components/Menu";
import Head from "next/head";
import styled from "styled-components";

const Header = styled.div`
  height: 8em;
  width: 100vw;
  display: flex;
  align-items: center;
  justify-content: space-between;
  .LogoHeader {
    margin-left: 1.5em;
  }
  .LogoMenu {
    margin-right: 1.5em;
  }
  a {
    cursor: pointer;
  }
`;
export default function Home() {
  return (
    <div>
      <Head>
        <title>CodeChella</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header className="Header">
        <div className="LogoHeader">
          <LogoSVG />
        </div>
        <div className="LogoMenu">
          <Menu />
        </div>
      </Header>
    </div>
  );
}
